<?php
return [
	'SUPER_ADMIN_ROLE_ID' => env('SUPER_ADMIN_ROLE_ID','1'),
	'ADMIN_ROLE_ID' => env('ADMIN_ROLE_ID','3'),
	'COMPANY_ADMIN_ROLE_ID' => env('COMPANY_ADMIN_ROLE_ID','4'),
	'SERVICE_ADMIN_ROLE_ID' => env('SERVICE_ADMIN_ROLE_ID','5'),
	'TECHNICIAN_ROLE_ID' => env('TECHNICIAN_ROLE_ID','6'),
	'COMPANY_USER_ROLE_ID' => env('COMPANY_USER_ROLE_ID','7'),
	'COMPANY_US' => env('COMPANY_US','7'),

	'GOOGLE_MAPS_API_KEY' =>  env('GOOGLE_MAPS_API_KEY','AIzaSyBsNVGUNzn19onCo93Vb1aupJO45oGrVMc'),

	'APP_URL' =>  env('APP_URL','http://jumbo-warranty.local')

];

?>